[API]
  ListenAddress = "/ip4/127.0.0.1/tcp/1234/http"
  RemoteListenAddress = ""
  Timeout = "30s"

[Backup]
  DisableMetadataLog = false

[Logging]

[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/0", "/ip6/::/tcp/0"]
  AnnounceAddresses = []
  NoAnnounceAddresses = []
  DisableNatPortMap = false
  ConnMgrLow = 150
  ConnMgrHigh = 180
  ConnMgrGrace = "20s"

[Pubsub]
  Bootstrapper = false
  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"

[Client]
  UseIpfs = false
  IpfsOnlineMode = false
  IpfsMAddr = ""
  IpfsUseForRetrieval = false
  SimultaneousTransfersForStorage = 20
  SimultaneousTransfersForRetrieval = 20
  OffChainRetrieval = false

[Chainstore]
  EnableSplitstore = false
  [Chainstore.Splitstore]
    ColdStoreType = ""
    HotStoreType = ""
    MarkSetType = ""
    HotStoreMessageRetention = 0
    HotStoreFullGCFrequency = 0
    EnableColdStoreAutoPrune = false
    ColdStoreFullGCFrequency = 0
    ColdStoreRetention = 0

[Fevm]
  # EnableEthRPC enables eth_ rpc, and enables storing a mapping of eth transaction hashes to filecoin message Cids.
  # This will also enable the RealTimeFilterAPI and HistoricFilterAPI by default, but they can be disabled by config options above.
  #
  # type: bool
  # env var: LOTUS_FEVM_ENABLEETHRPC
  EnableEthRPC = true

[Storage]
  [Storage.File]
    [Storage.File.CSV]
      Format = "CSV"
      Path = "/tmp"
      OmitHeader = false
      FilePattern = "{table}.csv"
  [Storage.Postgresql]
    [Storage.Postgresql.Database1]
      URLEnv = "LILY_STORAGE_POSTGRESQL_DB_URL"
      ApplicationName = "lily"
      SchemaName = "visor"
      PoolSize = 20
      AllowUpsert = false

[Queue]
  [Queue.Notifiers]
    [Queue.Notifiers.Notifier1]
        Network = "tcp"
        Addr = "REDIS_ADDRESS"
        Username = ""
        PasswordEnv = "LILY_REDIS_PASSWORD"
        DB = 0
        PoolSize = 0
  [Queue.Workers]
    [Queue.Workers.Worker1]
      [Queue.Workers.Worker1.RedisConfig]
        Network = "tcp"
        Addr = "REDIS_ADDRESS"
        Username = ""
        PasswordEnv = "LILY_REDIS_PASSWORD"
        DB = 0
        PoolSize = 0
      [Queue.Workers.Worker1.WorkerConfig]
        Concurrency = 1
        LoggerLevel = "debug"
        WatchQueuePriority = 5
        FillQueuePriority = 3
        IndexQueuePriority = 1
        WalkQueuePriority = 1
        StrictPriority = false
        ShutdownTimeout = 30000000000
